app14/urls.py
from django.urls import path
from app14.views import * 
app_name='something'

urlpatterns = [
    path('first/',first,name='first'),
    path('second/',second,name='second'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
from app13.views import *
import app14
urlpatterns = [
    path('admin/', admin.site.urls),
    path('third/',third,name='third'),
    path('fourth/',fourth,name='fourth'),
    path('app14/',include('app14.urls'))
]

app13/models.py
from django.db import models

# Create your models here.

app14/models.py
from django.db import models

# Create your models here.

app13/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'three.html')
def fourth(request):
    return render(request,'four.html')

app14/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'one.html')
def second(request):
    return render(request,'two.html')

templates/four.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>raja</h1>
        <a href="{% url 'something:first' %}"> go to first page </a> <br>
        <a href="{% url 'something:second' %}"> go to second page </a> <br>
        <a href="{% url 'third' %}"> go to third page</a>
    </center>
</body>
</html>

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>harish</h1>
    </center>
    <a href="{% url 'something:second' %}"> go to second page </a> <br>
    <a href="{% url 'third' %}"> go to third page </a> <br>
    <a href="{% url 'fourth' %}"> go to fourth page</a>
</body>
</html>

templates/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>govind</h1>
        <a href="{% url 'something:first' %}"> go to first page </a> <br>
        <a href="{% url 'something:second' %}"> go to second page </a> <br>
        <a href="{% url 'fourth' %}"> go to fourth page</a>
    </center>
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>malli</h1>
        <a href="{% url 'something:first' %}"> go to first page </a> <br>
    <a href="{% url 'third' %}"> go to third page </a> <br>
    <a href="{% url 'fourth' %}"> go to fourth page</a>
    </center>
</body>
</html>